name: Release binary builder

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update Ubuntu
      run: sudo apt update 
    
    - name: Install libs
      run: sudo apt install -y gcc-arm-none-eabi
  
    - name: Clone Blackmagic
      run: git clone https://github.com/blackmagic-debug/blackmagic.git
    
    - name: Run build target
      run: cd ./blackmagic && make PROBE_HOST=blackpill-f401cc
     
    - name: Build release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: |
          ${{runner.workspace}}/blackmagic/src/blackmagic.hex
          ${{runner.workspace}}/blackmagic/src/blackmagic.bin
